# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instacar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for instacar

  target 'instacar-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'instacarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


pod 'Firebase/Core'
pod 'FirebaseMessaging'